# Generated by Django 5.2.2 on 2025-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.IntegerField(max_length=11)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'signup_staff',
            },
        ),
    ]
